"""ORM models for the tenancy schema.

Every table lives here even when its migration is raw SQL. Alembic's
autogenerate diffs the live database against `Base.metadata`; a table missing
from the metadata is read as "dropped", and the next autogenerated revision
carries a `drop_table` for it.

RLS — ENABLE/FORCE, the policies, and the role grants — stays in the migrations.
SQLAlchemy has no metadata construct for any of it, so there is nothing here for
autogenerate to diff, and it leaves those objects alone.
"""

import enum
import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase): ...


class Vertical(enum.StrEnum):
    education = "education"
    realestate = "realestate"


class UsageKind(enum.StrEnum):
    message_in = "message_in"
    message_out = "message_out"
    llm_call = "llm_call"
    embedding_call = "embedding_call"
    tool_call = "tool_call"


class Tenant(Base):
    __tablename__ = "tenants"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    slug: Mapped[str] = mapped_column(String(64), unique=True, index=True)
    name: Mapped[str] = mapped_column(String(255))
    vertical: Mapped[Vertical] = mapped_column(Enum(Vertical, name="vertical"))
    default_lang: Mapped[str] = mapped_column(String(8), default="ar")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class Conversation(Base):
    """Mirrors migration 0002. Tenant-scoped: see the RLS policy there."""

    __tablename__ = "conversations"
    __table_args__ = (Index("ix_conversations_tenant_id", "tenant_id"),)

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("tenants.id"))
    state: Mapped[dict] = mapped_column(JSONB, server_default=text("'{}'::jsonb"))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class UsageLedger(Base):
    """Mirrors migration 0004. Append-only: moc_app holds no UPDATE or DELETE grant.

    Writes go through `moc.tenancy.metering.record_usage`, which sources
    `tenant_id` from the transaction rather than from its caller.
    """

    __tablename__ = "usage_ledger"
    __table_args__ = (Index("ix_usage_ledger_tenant_created", "tenant_id", "created_at"),)

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("tenants.id"))
    kind: Mapped[UsageKind] = mapped_column(Enum(UsageKind, name="usage_kind"))
    channel: Mapped[str | None] = mapped_column(Text, nullable=True)
    quantity: Mapped[int] = mapped_column(Integer, server_default=text("1"))
    model: Mapped[str | None] = mapped_column(Text, nullable=True)
    provider: Mapped[str | None] = mapped_column(Text, nullable=True)
    input_tokens: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    output_tokens: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    cached_tokens: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    provider_cost_usd: Mapped[Decimal | None] = mapped_column(Numeric(14, 6), nullable=True)
    degraded: Mapped[bool] = mapped_column(Boolean, server_default=text("false"))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
