"""ORM models for the tenancy schema.

Every table lives here even when its migration is raw SQL. Alembic's
autogenerate diffs the live database against `Base.metadata`; a table missing
from the metadata is read as "dropped", and the next autogenerated revision
carries a `drop_table` for it.

RLS — ENABLE/FORCE, the policies, and the role grants — stays in the migrations.
SQLAlchemy has no metadata construct for any of it, so there is nothing here for
autogenerate to diff, and it leaves those objects alone.
"""

import enum
import uuid
from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import (
    Boolean,
    Date,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase): ...


class Vertical(enum.StrEnum):
    education = "education"
    realestate = "realestate"


class UsageKind(enum.StrEnum):
    message_in = "message_in"
    message_out = "message_out"
    llm_call = "llm_call"
    embedding_call = "embedding_call"
    tool_call = "tool_call"


class Tenant(Base):
    __tablename__ = "tenants"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    slug: Mapped[str] = mapped_column(String(64), unique=True, index=True)
    name: Mapped[str] = mapped_column(String(255))
    vertical: Mapped[Vertical] = mapped_column(Enum(Vertical, name="vertical"))
    default_lang: Mapped[str] = mapped_column(String(8), default="ar")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class Conversation(Base):
    """Mirrors migration 0002. Tenant-scoped: see the RLS policy there."""

    __tablename__ = "conversations"
    __table_args__ = (
        Index("ix_conversations_tenant_id", "tenant_id"),
        # Mirrors 0005. Partial, because a conversation opened from the agent
        # inbox has no inbound sender and several of those must coexist.
        Index(
            "uq_conversations_thread",
            "tenant_id",
            "channel",
            "sender_ref",
            unique=True,
            postgresql_where=text("channel IS NOT NULL AND sender_ref IS NOT NULL"),
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("tenants.id"))
    state: Mapped[dict] = mapped_column(JSONB, server_default=text("'{}'::jsonb"))
    channel: Mapped[str | None] = mapped_column(Text, nullable=True)
    sender_ref: Mapped[str | None] = mapped_column(Text, nullable=True)
    channel_account_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )
    #: When the customer last wrote. The 24-hour service window (§6.2) is
    #: measured from here, so the outbound worker can tell whether a freeform
    #: reply is allowed without re-reading the inbound message.
    last_inbound_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class UsageLedger(Base):
    """Mirrors migration 0004. Append-only: moc_app holds no UPDATE or DELETE grant.

    Writes go through `moc.tenancy.metering.record_usage`, which sources
    `tenant_id` from the transaction rather than from its caller.
    """

    __tablename__ = "usage_ledger"
    __table_args__ = (Index("ix_usage_ledger_tenant_created", "tenant_id", "created_at"),)

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("tenants.id"))
    kind: Mapped[UsageKind] = mapped_column(Enum(UsageKind, name="usage_kind"))
    channel: Mapped[str | None] = mapped_column(Text, nullable=True)
    quantity: Mapped[int] = mapped_column(Integer, server_default=text("1"))
    model: Mapped[str | None] = mapped_column(Text, nullable=True)
    provider: Mapped[str | None] = mapped_column(Text, nullable=True)
    input_tokens: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    output_tokens: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    cached_tokens: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    provider_cost_usd: Mapped[Decimal | None] = mapped_column(Numeric(14, 6), nullable=True)
    degraded: Mapped[bool] = mapped_column(Boolean, server_default=text("false"))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


# ─────────────────────────── retrieval (migration 0006) ───────────────────────────
#
# These live here rather than under `moc.retrieval` because Alembic reads one
# `Base.metadata`, and the drift job asserts autogenerate produces nothing. A
# second declarative base would mean a second metadata, and the table absent
# from the one Alembic sees would be read as dropped.


class KbDocument(Base):
    """Mirrors migration 0006. Tenant-scoped: RLS policy lives there."""

    __tablename__ = "kb_documents"
    __table_args__ = (
        Index("uq_kb_documents_tenant_doc", "tenant_id", "doc_id", unique=True),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("tenants.id"))
    #: The tenant's own stable identifier for the source document.
    doc_id: Mapped[str] = mapped_column(Text)
    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    vertical: Mapped[str] = mapped_column(Text)
    lang: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_uri: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class KbChunk(Base):
    """Mirrors migration 0006.

    Holds both forms of the text (§7.1): `content` is what a reply quotes,
    `content_normalized` is what retrieval matches. `embedding_version` is per
    row so a model change is a tracked backfill rather than a silent reindex.
    """

    __tablename__ = "kb_chunks"
    __table_args__ = (
        Index("uq_kb_chunks_tenant_chunk", "tenant_id", "chunk_id", unique=True),
        Index("ix_kb_chunks_document", "document_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("tenants.id"))
    document_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("kb_documents.id", ondelete="CASCADE")
    )
    chunk_id: Mapped[str] = mapped_column(Text)
    ordinal: Mapped[int] = mapped_column(Integer)
    content: Mapped[str] = mapped_column(Text)
    content_normalized: Mapped[str] = mapped_column(Text)
    lang: Mapped[str | None] = mapped_column(Text, nullable=True)
    topic: Mapped[str | None] = mapped_column(Text, nullable=True)
    entity_ref: Mapped[str | None] = mapped_column(Text, nullable=True)
    #: Null means the source states no date. A pipeline defaulting these to
    #: now() would silently make every fee current (§7.1).
    effective_from: Mapped[date | None] = mapped_column(Date, nullable=True)
    effective_to: Mapped[date | None] = mapped_column(Date, nullable=True)
    embedding_version: Mapped[str] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class KbOutbox(Base):
    """Mirrors migration 0006.

    Written in the same transaction as the chunks it describes, so there is no
    window where a chunk exists and nothing knows to index it.
    """

    __tablename__ = "kb_outbox"
    __table_args__ = (
        Index(
            "ix_kb_outbox_pending",
            "tenant_id",
            "created_at",
            postgresql_where=text("status = 'pending'"),
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("tenants.id"))
    chunk_id: Mapped[str] = mapped_column(Text)
    target: Mapped[str] = mapped_column(Text)
    op: Mapped[str] = mapped_column(Text)
    #: UUIDv5 of chunk_id, so a replay upserts rather than duplicates (§7.1).
    point_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True))
    status: Mapped[str] = mapped_column(Text, server_default=text("'pending'"))
    attempts: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    last_error: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    processed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
